# Generated by Django 2.1.7 on 2020-01-28 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='authors',
            field=models.ManyToManyField(related_name='channels_author', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='followed_by',
            field=models.ManyToManyField(related_name='followings_channel', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
    ]
