# Generated by Django 2.1.7 on 2020-02-03 10:11

from django.db import migrations, models
import django.db.models.deletion
import socials.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20200128_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, upload_to=socials.models.channel_avatar_path, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='channel',
            name='rules',
            field=models.TextField(blank=True, help_text='rules of this channel'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, upload_to=socials.models.post_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socials.Channel'),
        ),
    ]
