# Generated by Django 2.1.7 on 2020-02-03 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0003_auto_20200203_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='feedback',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=32, validators=[djchoices.choices.ChoicesValidator({'NEGATIVE': 'NEGATIVE', 'POSITIVE': 'POSITIVE'})]),
        ),
    ]
