# Generated by Django 2.1.7 on 2020-02-03 18:16

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_auto_20200203_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='feedback',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=32, null=True, validators=[djchoices.choices.ChoicesValidator({'NEGATIVE': 'NEGATIVE', 'POSITIVE': 'POSITIVE'})]),
        ),
    ]
