# Generated by Django 2.1.7 on 2020-02-09 20:15

from django.db import migrations
import socials.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0010_auto_20200209_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, upload_to=socials.models.comment_image_path, verbose_name='image'),
        ),
    ]
