# Generated by Django 2.1.7 on 2020-01-28 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(related_name='followings_user', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
    ]
