# Generated by Django 2.1.7 on 2020-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200204_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verfy_code',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
